services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: vvveb
      POSTGRES_DB: vvveb
      POSTGRES_USER: vvveb
      POSTGRES_PASSWORD: vvveb
    volumes:
      - db:/var/lib/postgres
    networks:
      - internal

  php:
    image: vvveb/vvvebcms:latest
    environment:
      DB_HOST: db
      DB_DATABASE: vvveb
      DB_USER: vvveb
      DB_PASSWORD: vvveb
      DB_ENGINE: pgsql #sqlite,mysqli
    volumes:
      - vvveb-volume:/var/www/html
      - db:/var/lib/postgres
    ports:
      - "8080:80"
    links:
      - db:pgsql
    depends_on:
      - db
    networks:
      - internal


volumes:
  vvveb-volume:
  db:

networks:
  internal:
    driver: bridge
